import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';
import { Reactqueryprovider } from "./Reactqueryprovider";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Reactqueryprovider>
        {children}
        <Toaster richColors  position="bottom-right"/>
        </Reactqueryprovider>
        </body>
    </html>
  );
}
